### ISSUE TITLE
Is mo2 booting not supported?

### ISSUE THREAD

**Issue by qweqwedasdas** [Perchik71/SkyrimSETest#3]

**Comment by qweqwedasdas** [comment]
I can't start sseck loader directly in mo2

**Comment by Perchik71** [comment]
In MO2, you can run absolutely any application, you just need to add it to the list. See the MO2 wiki.

**Comment by qweqwedasdas** [comment]
> In MO2, you can run absolutely any application, you just need to add it to the list. See the MO2 wiki.

I used mo2 to start sseck_loader, but it suddenly failed to start, so I can only start sseck_loader manually in Skyrim Anniversary Edition game folder
